version: '3.8'

services:
  next-app:
    stdin_open: true
    container_name: next-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_DOMAIN: 'http://next-app-container:3000/api/submitForm'
      POSTGRES_PRISMA_URL: 'postgres://default:LEg8zasdfY3p@ep-rough-mode-a7m7hxyd-pooler.ap-southeast-2.aws.neon.tech:5432/fcl-db?sslmode=require&pgbouncer=true&connect_timeout=15'
    image: krismile98/next-app:1.0
